# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mete Kabak
email: kabakmete@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Ruby & Php developer developer, fall in love with single page application frameworks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://metekabak.github.io" # the base hostname & protocol for your site
twitter_username: metekabak
github_username:  metekabak

# Build settings
markdown: kramdown
permalink: blog/:categories/:title/
